sudo: required
services:
    - docker

before_install:
    - docker build -t nexter21/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true nexter21/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-484725107874"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

